In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("Telco-Customer-Churn.csv")

In [44]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [45]:
df.drop(['customerID'], inplace = True, axis = 1)

In [66]:
df.dtypes

gender                         int64
SeniorCitizen                  int64
Partner                        int64
Dependents                     int64
tenure                         int64
PhoneService                   int64
MultipleLines                  int64
OnlineSecurity                 int64
OnlineBackup                   int64
DeviceProtection               int64
TechSupport                    int64
StreamingTV                    int64
StreamingMovies                int64
PaperlessBilling               int64
MonthlyCharges               float64
TotalCharges                 float64
Churn                          int64
DSL                            uint8
Fiber optic                    uint8
No                             uint8
Month-to-month                 uint8
One year                       uint8
Two year                       uint8
Bank transfer (automatic)      uint8
Credit card (automatic)        uint8
Electronic check               uint8
Mailed check                   uint8
dtype: object

In [47]:
for i in ['Partner', 'Dependents', 'PhoneService', 'MultipleLines','OnlineSecurity', 'OnlineBackup', 'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling']:
    df[i]=df[i].apply(lambda x: 1 if x=="Yes" else 0)

In [48]:
df.gender=df.gender.apply(lambda x: 1 if x=="Female" else 0)

In [49]:
dummy1 = pd.get_dummies(df['InternetService']);

In [50]:
df = pd.concat([df, dummy1], axis = 1)

In [51]:
df = df.drop(['InternetService'], axis =1)

In [52]:
df.Contract.unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [53]:
dummy2 = pd.get_dummies(df['Contract']);

In [54]:
df = pd.concat([df, dummy2], axis = 1)

In [55]:
df = df.drop(['Contract'], axis =1)

In [56]:
dummy3 = pd.get_dummies(df['PaymentMethod']);

In [57]:
df = pd.concat([df, dummy3], axis = 1)

In [58]:
df = df.drop(['PaymentMethod'], axis =1)

In [59]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,DSL,Fiber optic,No,Month-to-month,One year,Two year,Bank transfer (automatic),Credit card (automatic),Electronic check,Mailed check
0,1,0,1,0,1,0,0,0,1,0,...,1,0,0,1,0,0,0,0,1,0
1,0,0,0,0,34,1,0,1,0,1,...,1,0,0,0,1,0,0,0,0,1
2,0,0,0,0,2,1,0,1,1,0,...,1,0,0,1,0,0,0,0,0,1
3,0,0,0,0,45,0,0,1,0,1,...,1,0,0,0,1,0,1,0,0,0
4,1,0,0,0,2,1,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,1,0,1,...,1,0,0,0,1,0,0,0,0,1
7039,1,0,1,1,72,1,1,0,1,1,...,0,1,0,0,1,0,0,1,0,0
7040,1,0,1,1,11,0,0,1,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,0,1,1,0,4,1,1,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,0,0,0,0,66,1,0,1,0,1,...,0,1,0,0,0,1,1,0,0,0

In [60]:
df.Churn=df.Churn.apply(lambda x: 1 if x=="Yes" else 0)

In [61]:
df['TotalCharges'].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

In [62]:
df = df[df["TotalCharges"].str.strip() != ""]

In [63]:
df.TotalCharges=pd.to_numeric(df.TotalCharges)

C:\Users\ahana\AppData\Local\Temp\ipykernel_10184\680514069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.TotalCharges=pd.to_numeric(df.TotalCharges)

In [64]:
from sklearn.preprocessing import MinMaxScaler

In [67]:
scaler = MinMaxScaler()

In [68]:
scalingcolums = ['tenure', 'MonthlyCharges', 'TotalCharges']
df[scalingcolums] = scaler.fit_transform(df[scalingcolums])

C:\Users\ahana\AppData\Local\Temp\ipykernel_10184\4206623072.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[scalingcolums] = scaler.fit_transform(df[scalingcolums])

In [69]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,DSL,Fiber optic,No,Month-to-month,One year,Two year,Bank transfer (automatic),Credit card (automatic),Electronic check,Mailed check
0,1,0,1,0,0.000000,0,0,0,1,0,...,1,0,0,1,0,0,0,0,1,0
1,0,0,0,0,0.464789,1,0,1,0,1,...,1,0,0,0,1,0,0,0,0,1
2,0,0,0,0,0.014085,1,0,1,1,0,...,1,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0.619718,0,0,1,0,1,...,1,0,0,0,1,0,1,0,0,0
4,1,0,0,0,0.014085,1,0,0,0,0,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,0.323944,1,1,1,0,1,...,1,0,0,0,1,0,0,0,0,1
7039,1,0,1,1,1.000000,1,1,0,1,1,...,0,1,0,0,1,0,0,1,0,0
7040,1,0,1,1,0.140845,0,0,1,0,0,...,1,0,0,1,0,0,0,0,1,0
7041,0,1,1,0,0.042254,1,1,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,0,0,0,0,0.915493,1,0,1,0,1,...,0,1,0,0,0,1,1,0,0,0

In [77]:
import tensorflow as tf

In [80]:
import tensorflow.keras as tf

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X = df.drop("Churn", axis=1)
Y= df.Churn

In [73]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y,test_size = 0.2)

In [74]:
X.shape

(7032, 26)

In [75]:
Y.shape

(7032,)

In [104]:
model = tf.models.Sequential([
    tf.layers.Dense(50,input_shape=(26,),activation="relu"),
    tf.layers.Dense(35,activation="relu"),
    keras.layers.Dropout(0.2),
    tf.layers.Dense(27,activation = "relu"),
    tf.layers.Dense(12,activation="relu"),
    tf.layers.Dense(4,activation="relu"),
    keras.layers.Dropout(0.2),
    tf.layers.Dense(1, activation="sigmoid")
])

In [105]:
model.compile(loss=tf.losses.binary_crossentropy,optimizer="adam",metrics=["accuracy"])

In [106]:
model.fit(xtrain,ytrain,epochs=62,)

Epoch 1/62
176/176 [==============================] - 4s 5ms/step - loss: 0.5337 - accuracy: 0.7255
Epoch 2/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4762 - accuracy: 0.7655
Epoch 3/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4583 - accuracy: 0.7749
Epoch 4/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4537 - accuracy: 0.7844
Epoch 5/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4506 - accuracy: 0.7810
Epoch 6/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4516 - accuracy: 0.7813
Epoch 7/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4420 - accuracy: 0.7860
Epoch 8/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4434 - accuracy: 0.7851
Epoch 9/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4409 - accuracy: 0.7870
Epoch 10/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4402 - accuracy: 0.7908
Epoch 11/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4374 - accuracy: 0.7883
Epoch 12/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4306 - accuracy: 0.7931
Epoch 13/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4315 - accuracy: 0.7892
Epoch 14/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4322 - accuracy: 0.7909
Epoch 15/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4295 - accuracy: 0.7980
Epoch 16/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4308 - accuracy: 0.7899
Epoch 17/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4206 - accuracy: 0.7988
Epoch 18/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4237 - accuracy: 0.7988
Epoch 19/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4293 - accuracy: 0.7925
Epoch 20/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4234 - accuracy: 0.7973
Epoch 21/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4225 - accuracy: 0.7996
Epoch 22/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4242 - accuracy: 0.7934
Epoch 23/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4201 - accuracy: 0.7931
Epoch 24/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4146 - accuracy: 0.8027
Epoch 25/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4144 - accuracy: 0.7998
Epoch 26/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4184 - accuracy: 0.8002
Epoch 27/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4150 - accuracy: 0.7991
Epoch 28/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4121 - accuracy: 0.8043
Epoch 29/62
176/176 [==============================] - 1s 5ms/step - loss: 0.4089 - accuracy: 0.8009
Epoch 30/62
176/176 [==============================] - 1s 4ms/step - loss: 0.4048 - accuracy: 0.8057
Epoch 31/62
176/176 [==============================] - 1s 4ms/step - loss: 0.4080 - accuracy: 0.8030
Epoch 32/62
176/176 [==============================] - 1s 4ms/step - loss: 0.4002 - accuracy: 0.8055
Epoch 33/62
176/176 [==============================] - 1s 4ms/step - loss: 0.4039 - accuracy: 0.8066
Epoch 34/62
176/176 [==============================] - 1s 4ms/step - loss: 0.3967 - accuracy: 0.8053
Epoch 35/62
176/176 [==============================] - 1s 4ms/step - loss: 0.3935 - accuracy: 0.8098
Epoch 36/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3981 - accuracy: 0.8082
Epoch 37/62
176/176 [==============================] - 1s 4ms/step - loss: 0.3891 - accuracy: 0.8069
Epoch 38/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3901 - accuracy: 0.8084
Epoch 39/62
176/176 [==============================] - 1s 4ms/step - loss: 0.3911 - accuracy: 0.8091
Epoch 40/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3859 - accuracy: 0.8132
Epoch 41/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3844 - accuracy: 0.8098
Epoch 42/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3822 - accuracy: 0.8078
Epoch 43/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3826 - accuracy: 0.8144
Epoch 44/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3751 - accuracy: 0.8204
Epoch 45/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3778 - accuracy: 0.8133
Epoch 46/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3808 - accuracy: 0.8116
Epoch 47/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3729 - accuracy: 0.8185
Epoch 48/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3725 - accuracy: 0.8144
Epoch 49/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3663 - accuracy: 0.8231
Epoch 50/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3671 - accuracy: 0.8142
Epoch 51/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3658 - accuracy: 0.8165
Epoch 52/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3617 - accuracy: 0.8208
Epoch 53/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3639 - accuracy: 0.8192
Epoch 54/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3647 - accuracy: 0.8190
Epoch 55/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3610 - accuracy: 0.8208
Epoch 56/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3607 - accuracy: 0.8210
Epoch 57/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3576 - accuracy: 0.8148
Epoch 58/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3632 - accuracy: 0.8224
Epoch 59/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3556 - accuracy: 0.8187
Epoch 60/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3610 - accuracy: 0.8185
Epoch 61/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3503 - accuracy: 0.8267
Epoch 62/62
176/176 [==============================] - 1s 5ms/step - loss: 0.3488 - accuracy: 0.8194

In [107]:
model.evaluate(xtest,ytest)

44/44 [==============================] - 1s 3ms/step - loss: 0.5074 - accuracy: 0.7982

[0.5073897838592529, 0.7981520891189575]

In [108]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 50)                1350

 dense_31 (Dense)            (None, 35)                1785

 dropout (Dropout)           (None, 35)                0

 dense_32 (Dense)            (None, 27)                972

 dense_33 (Dense)            (None, 12)                336

 dense_34 (Dense)            (None, 4)                 52

 dropout_1 (Dropout)         (None, 4)                 0

 dense_35 (Dense)            (None, 1)                 5

=================================================================
Total params: 4500 (17.58 KB)
Trainable params: 4500 (17.58 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [110]:
import pickle

In [111]:
with open("Churn_Prediction.pickle","wb") as f:
    pickle.dump(model,f)